<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SurajKumarSatya" failures="1" tests="3" name="ErrorValidationTest" time="31.999" errors="0" timestamp="2023-10-02T23:47:47 IST">
  <testcase classname="websitesAutomate.ErrorValidationTest" name="loginErrorVal" time="3.753">
    <skipped/>
  </testcase> <!-- loginErrorVal -->
  <testcase classname="websitesAutomate.ErrorValidationTest" name="loginErrorVal" time="3.601">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Usernam and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Usernam and password do not match any user in this service]
at websitesAutomate.ErrorValidationTest.loginErrorVal(ErrorValidationTest.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorVal -->
  <testcase classname="websitesAutomate.ErrorValidationTest" name="productErrorValidation" time="8.958"/>
</testsuite> <!-- ErrorValidationTest -->
