<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-02T23:47:14 IST" name="Suite" finished-at="2023-10-02T23:47:46 IST" duration-ms="31999">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginErrorVal()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" name="loginErrorVal" class="websitesAutomate.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2023-10-02T23:47:14 IST" name="WebsiteAutomate" finished-at="2023-10-02T23:47:27 IST" duration-ms="12665">
      <class name="websitesAutomate.WebsiteAutomate">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:websitesAutomate.WebsiteAutomate@6dab9b6d]" started-at="2023-10-02T23:47:15 IST" name="launchApplication" finished-at="2023-10-02T23:47:22 IST" duration-ms="7313" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="websiteAutomateTest()[pri:0, instance:websitesAutomate.WebsiteAutomate@6dab9b6d]" started-at="2023-10-02T23:47:22 IST" name="websiteAutomateTest" finished-at="2023-10-02T23:47:27 IST" duration-ms="5036" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- websiteAutomateTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:websitesAutomate.WebsiteAutomate@6dab9b6d]" started-at="2023-10-02T23:47:27 IST" name="tearDown" finished-at="2023-10-02T23:47:27 IST" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- websitesAutomate.WebsiteAutomate -->
    </test> <!-- WebsiteAutomate -->
    <test started-at="2023-10-02T23:47:14 IST" name="ErrorValidationTest" finished-at="2023-10-02T23:47:46 IST" duration-ms="31999">
      <class name="websitesAutomate.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:15 IST" name="launchApplication" finished-at="2023-10-02T23:47:22 IST" duration-ms="7099" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorVal()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:22 IST" name="loginErrorVal" finished-at="2023-10-02T23:47:25 IST" duration-ms="3753" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Usernam and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Usernam and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at websitesAutomate.ErrorValidationTest.loginErrorVal(ErrorValidationTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorVal -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:25 IST" name="tearDown" finished-at="2023-10-02T23:47:26 IST" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:26 IST" name="launchApplication" finished-at="2023-10-02T23:47:30 IST" duration-ms="4225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorVal()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:30 IST" name="loginErrorVal" finished-at="2023-10-02T23:47:33 IST" duration-ms="3601" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Usernam and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service] but found [Epic sadface: Usernam and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at websitesAutomate.ErrorValidationTest.loginErrorVal(ErrorValidationTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorVal -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:34 IST" name="tearDown" finished-at="2023-10-02T23:47:34 IST" duration-ms="135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:34 IST" name="launchApplication" finished-at="2023-10-02T23:47:37 IST" duration-ms="3548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:37 IST" name="productErrorValidation" finished-at="2023-10-02T23:47:46 IST" duration-ms="8958" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:websitesAutomate.ErrorValidationTest@176b3f44]" started-at="2023-10-02T23:47:46 IST" name="tearDown" finished-at="2023-10-02T23:47:46 IST" duration-ms="109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- websitesAutomate.ErrorValidationTest -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
